shared:
  system_profiles:
    train_default: ${oc.select:system.training,{}}
    infer_default: ${oc.select:system.inference,{}}
  data_transform_profiles:
    default:
      data_transform: ${oc.select:data.data_transform,null}
      image_transform: ${oc.select:data.image_transform,null}
      nnunet_preprocessing: ${oc.select:data.nnunet_preprocessing,null}
  inference_profiles:
    default: ${oc.select:inference,{}}

# Shared tutorial defaults used by top-level tutorials/*.yaml.

system:
  training:
    num_gpus: 1
    num_workers: 1
    batch_size: 1
  inference:
    num_gpus: 1
    num_workers: 1
    batch_size: 1
  seed: 42


model:
  in_channels: 1

  losses:
    - function: DiceLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']
    - function: BCEWithLogitsLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']
data:
  image_transform:
    normalize: "0-1"

optimization:
  optimizer:
    betas: [0.9, 0.999]

monitor:
  detect_anomaly: false
  logging:
    scalar:
      benchmark: true
    images:
      enabled: true
      selected_channels:
  checkpoint:
    mode: min
    save_last: true
    use_timestamp: true

inference:
  test_time_augmentation:
    ensemble_mode: mean
