# Shared tutorial defaults used by top-level tutorials/*.yaml.

system:
  training:
    num_gpus: 1
    num_workers: 1
    batch_size: 1
  inference:
    num_gpus: 1
    num_workers: 1
    batch_size: 1
  seed: 42


model:
  in_channels: 1

  loss_terms:
    - name: loss_0
      loss_index: 0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']
      task_name: supervised
    - name: loss_1
      loss_index: 1
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']
      task_name: supervised
data:
  image_transform:
    normalize: "0-1"

optimization:
  optimizer:
    betas: [0.9, 0.999]

monitor:
  detect_anomaly: false
  logging:
    scalar:
      benchmark: true
    images:
      enabled: true
      selected_channels:
  checkpoint:
    mode: min
    save_last: true
    use_timestamp: true

inference:
  test_time_augmentation:
    ensemble_mode: mean
