_base_: common.yaml

model:
  architecture: monai_unet
  filters: [32, 64, 128, 256]

data:
  use_preloaded_cache_train: true
  use_preloaded_cache_val: true
  iter_num_per_epoch: 1280
  image_transform:
    clip_percentile_low: 0.0
    clip_percentile_high: 1.0

optimization:
  max_epochs: 1000
  accumulate_grad_batches: 1
  precision: "bf16-mixed"
  optimizer:
    lr: 0.001
    eps: 1.0e-8
  scheduler:
    min_lr: 1.0e-6

monitor:
  early_stopping:
    enabled: true
    monitor: train_loss_total_epoch
    mode: min
    check_finite: true
  logging:
    scalar:
      loss: [train_loss_total_epoch]
      loss_every_n_steps: 10
      val_check_interval: 1.0
    images:
      log_every_n_epochs: 1
  checkpoint:
    save_top_k: 1
    save_every_n_epochs: 10

inference:
  sliding_window:
    blending: gaussian
    sigma_scale: 0.25
  test_time_augmentation:
    enabled: true
    select_channel: null
  save_prediction:
    enabled: true
    intensity_scale: 255
    intensity_dtype: uint8
