activation_profiles:
  act_binary:
    channel_activations:
      - {channels: ":", activation: sigmoid}

  act_bcd:
    channel_activations:
      - {channels: "0:2", activation: sigmoid}
      - {channels: "2:3", activation: tanh}

  act_bd:
    channel_activations:
      - {channels: "0:-1", activation: sigmoid}
      - {channels: "-1:", activation: tanh}
