label_profiles:
  label_bcd:
    targets:
      - name: binary
        kwargs: {}
      - name: instance_boundary
        kwargs:
          thickness: 1
          edge_mode: all
          mode: 2d
      - name: instance_edt
        kwargs:
          mode: "2d"
  label_affinity_9:
    erosion: 1
    targets:
      - name: affinity
        kwargs:
          offsets: ["0-0-1", "0-1-0", "1-0-0", "0-0-3", "0-3-0", "3-0-0", "0-0-9", "0-9-0", "9-0-0"]
          deepem_crop: true
  label_aff9_sdt:
    erosion: 1
    targets:
      - name: affinity
        kwargs:
          offsets: ["0-0-1", "0-1-0", "1-0-0", "0-0-5", "0-5-0", "5-0-0", "0-0-17", "0-17-0", "17-0-0"]
          deepem_crop: true
      - name: skeleton_aware_edt
        kwargs:
          alpha: 0.8
          bg_value: -1.0

  label_aff12:
    erosion: 1
    targets:
      - name: affinity
        kwargs:
          offsets: ["0-0-1", "0-1-0", "1-0-0", "2-0-0", "3-0-0", "4-0-0", "0-0-3", "0-0-9", "0-0-27", "0-3-0", "0-9-0", "0-27-0"]
          deepem_crop: true
