_base_: ../bases/common.yaml
model:
  architecture: monai_basic_unet3d
  in_channels: 1
  out_channels: 2
  filters: [32, 64, 128, 256, 512]
  dropout: 0.1

  losses:
    - function: DiceLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']
    - function: BCEWithLogitsLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']

data:
  # Data paths (modify for your dataset)
  train_image: "datasets/lucchi/train_image.h5"
  train_label: "datasets/lucchi/train_label.h5"
  val_image: "datasets/lucchi/val_image.h5"
  val_label: "datasets/lucchi/val_label.h5"

  patch_size: [128, 128, 128]

  # Super-resolution focused augmentation
  augmentation:
    preset: some
    # CutBlur (primary augmentation for super-resolution)
    # Forces model to learn from degraded (low-res) regions
    cut_blur:
      enabled: true
      prob: 0.8  # High probability
      length_ratio: 0.5  # Larger regions (50% of volume)
      down_ratio_range: [2.0, 8.0]  # 2x-8x downsampling
      downsample_z: false  # Keep z-resolution (anisotropic)
    # Misalignment (mild, to prevent oversmoothing)
    misalignment:
      enabled: true
      prob: 0.3
      displacement: 10
      rotate_ratio: 0.0
    # Motion blur (creates directional blur)
    motion_blur:
      enabled: true
      prob: 0.4
      sections: [1, 2]
      kernel_size: 7  # Smaller kernel
    # Standard intensity augmentation
    intensity:
      enabled: true
      shift_intensity_prob: 0.5
      shift_intensity_offset: 0.1
      gaussian_noise_prob: 0.3
      gaussian_noise_std: 0.05  # Lower noise

optimization:
  max_epochs: 100
  precision: "16-mixed"
  gradient_clip_val: 1.0
  log_every_n_steps: 50
  optimizer:
    name: AdamW
    lr: 1e-4
    weight_decay: 1e-4
  scheduler:
    name: CosineAnnealingLR
    warmup_epochs: 5

monitor:
  checkpoint:
    monitor: "val/loss"
    mode: "min"
    save_top_k: 3
    save_last: true

train:
  system:
    overrides:
      num_gpus: 1
      num_workers: 4
      batch_size: 2
      seed: 42
