shared:
  system_profiles:
    train_default: ${oc.select:system.training,{}}
    infer_default: ${oc.select:system.inference,{}}
  data_transform_profiles:
    default:
      data_transform: ${oc.select:data.data_transform,null}
      image_transform: ${oc.select:data.image_transform,null}
      nnunet_preprocessing: ${oc.select:data.nnunet_preprocessing,null}
  inference_profiles:
    default: ${oc.select:inference,{}}

# Instance Segmentation Augmentation Preset
# Use case: Neuron instance segmentation, object detection
# Training speed: Slower (copy-paste is expensive)
# Model robustness: Excellent for instance segmentation

system:
  training:
    num_gpus: 1
    batch_size: 2
    num_workers: 4
  seed: 42

model:
  architecture: monai_basic_unet3d
  in_channels: 1
  out_channels: 2
  filters: [32, 64, 128, 256, 512]
  dropout: 0.1

  losses:
    - function: DiceLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']
    - function: BCEWithLogitsLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']

data:
  # Data paths (modify for your dataset)
  train_image: "datasets/lucchi/train_image.h5"
  train_label: "datasets/lucchi/train_label.h5"
  val_image: "datasets/lucchi/val_image.h5"
  val_label: "datasets/lucchi/val_label.h5"

  patch_size: [128, 128, 128]

  # Instance segmentation focused augmentation
  augmentation:
    preset: some
    # Copy-paste (primary augmentation for instance segmentation)
    # Copies objects, transforms them, pastes in non-overlapping regions
    copy_paste:
      enabled: true
      prob: 0.6
      max_obj_ratio: 0.7  # Skip if object too large
      rotation_angles: [30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330]
      border: 3
    # Misalignment and missing_section apply to both image and label in train pipeline
    misalignment:
      enabled: true
      prob: 0.5
      displacement: 16
      rotate_ratio: 0.5
    missing_section:
      enabled: true
      prob: 0.3
      num_sections: 1
    # Mixup (regularization for small datasets)
    # Note: This requires batch size > 1
    mixup:
      enabled: true
      prob: 0.3
      alpha_range: [0.7, 0.9]
    # Standard intensity augmentation (image only)
    intensity:
      enabled: true
      shift_intensity_prob: 0.5
      shift_intensity_offset: 0.1
      contrast_prob: 0.5
      contrast_range: [0.9, 1.1]
      gaussian_noise_prob: 0.5
      gaussian_noise_std: 0.1
    # Spatial augmentation (apply to both)
    # affine:
    #   enabled: true
    #   prob: 0.5
    #   rotate_range: [0.2, 0.2, 0.2]
    #   scale_range: [0.1, 0.1, 0.1]

optimization:
  max_epochs: 100
  precision: "16-mixed"
  gradient_clip_val: 1.0
  log_every_n_steps: 50
  optimizer:
    name: AdamW
    lr: 1e-4
    weight_decay: 1e-4
  scheduler:
    name: CosineAnnealingLR
    warmup_epochs: 5

monitor:
  checkpoint:
    monitor: "val/loss"
    mode: "min"
    save_top_k: 3
    save_last: true
