shared:
  system_profiles:
    train_default: ${oc.select:system.training,{}}
    infer_default: ${oc.select:system.inference,{}}
  data_transform_profiles:
    default:
      data_transform: ${oc.select:data.data_transform,null}
      image_transform: ${oc.select:data.image_transform,null}
      nnunet_preprocessing: ${oc.select:data.nnunet_preprocessing,null}
  inference_profiles:
    default: ${oc.select:inference,{}}

# Light EM Augmentation Preset
# Use case: Quick experiments, large datasets, fast iteration
# Training speed: Fast (minimal overhead)
# Model robustness: Basic

system:
  training:
    num_gpus: 1
    batch_size: 2
    num_workers: 4
  seed: 42

model:
  architecture: monai_basic_unet3d
  in_channels: 1
  out_channels: 2
  filters: [32, 64, 128, 256, 512]
  dropout: 0.1

  losses:
    - function: DiceLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']
    - function: BCEWithLogitsLoss
      weight: 1.0
      pred_slice: [0, '${model.out_channels}']
      target_slice: [0, '${model.out_channels}']

data:
  # Data paths (modify for your dataset)
  train_image: "datasets/lucchi/train_image.h5"
  train_label: "datasets/lucchi/train_label.h5"
  val_image: "datasets/lucchi/val_image.h5"
  val_label: "datasets/lucchi/val_label.h5"

  patch_size: [128, 128, 128]

  # Light augmentation strategy
  augmentation:
    preset: some
    # Missing sections (low probability)
    missing_section:
      enabled: true
      prob: 0.3
      num_sections: 1
    # Misalignment (translation only, low probability)
    misalignment:
      enabled: true
      prob: 0.3
      displacement: 8
      rotate_ratio: 0.0  # Translation only (faster)

optimization:
  max_epochs: 100
  precision: "16-mixed"
  gradient_clip_val: 1.0
  log_every_n_steps: 50
  optimizer:
    name: AdamW
    lr: 1e-4
    weight_decay: 1e-4
  scheduler:
    name: CosineAnnealingLR
    warmup_epochs: 5

monitor:
  checkpoint:
    monitor: "val/loss"
    mode: "min"
    save_top_k: 3
    save_last: true
