"""Modern Hydra-based configuration system for PyTorch Connectomics.

This module is a compatibility facade.
The schema dataclasses are implemented under ``connectomics.config.schema``
and re-exported here to preserve existing import paths.
"""

from __future__ import annotations

from .schema import (
    AffinityConfig,
    AffineConfig,
    AugmentationConfig,
    BinaryPostprocessingConfig,
    CheckpointConfig,
    Config,
    ConnectedComponentsConfig,
    CopyPasteConfig,
    CutBlurConfig,
    CutNoiseConfig,
    DataConfig,
    DataInputConfig,
    DataTransformConfig,
    DataTransformProfileConfig,
    DecodeBinaryContourDistanceWatershedConfig,
    DecodeModeConfig,
    DecodingParameterSpace,
    DataloaderConfig,
    EarlyStoppingConfig,
    EdgeModeConfig,
    ElasticConfig,
    EvaluationConfig,
    FlipConfig,
    ImageLoggingConfig,
    ImageTransformConfig,
    InferenceConfig,
    InferenceDataConfig,
    IntensityConfig,
    LabelTargetConfig,
    LabelTransformConfig,
    LoggingConfig,
    LossConfig,
    MisalignmentConfig,
    MissingPartsConfig,
    MissingSectionConfig,
    MixupConfig,
    MonaiConfig,
    ModelArchConfig,
    ModelConfig,
    MedNeXtConfig,
    MonitorConfig,
    MotionBlurConfig,
    NNUNetConfig,
    NNUNetPreprocessingConfig,
    RSUNetConfig,
    NaNDetectionConfig,
    OptimizationConfig,
    OptimizerConfig,
    ParameterConfig,
    ParameterSpaceConfig,
    PostprocessingConfig,
    PostprocessingParameterSpace,
    PredictionSavingConfig,
    RotateConfig,
    SavePredictionConfig,
    ScalarLoggingConfig,
    SchedulerConfig,
    SharedConfig,
    SkeletonDistanceConfig,
    SlidingWindowConfig,
    StripeConfig,
    SystemConfig,
    TransformerConfig,
    TestConfig,
    TestTimeAugmentationConfig,
    TrainConfig,
    TuneConfig,
    TuneOutputConfig,
    WandbConfig,
    configure_edge_mode,
    configure_instance_segmentation,
)

__all__ = [
    # Main configuration class
    "Config",
    "SharedConfig",
    "TrainConfig",
    # System configuration
    "SystemConfig",
    # Model configuration
    "ModelConfig",
    "ModelArchConfig",
    "MonaiConfig",
    "TransformerConfig",
    "MedNeXtConfig",
    "RSUNetConfig",
    "NNUNetConfig",
    "LossConfig",
    # Data configuration
    "DataInputConfig",
    "DataConfig",
    "DataloaderConfig",
    "DataTransformConfig",
    "DataTransformProfileConfig",
    "ImageTransformConfig",
    "NNUNetPreprocessingConfig",
    "LabelTransformConfig",
    "AffinityConfig",
    "SkeletonDistanceConfig",
    "LabelTargetConfig",
    "EdgeModeConfig",
    # Optimization configuration
    "OptimizationConfig",
    "OptimizerConfig",
    "SchedulerConfig",
    # Monitoring configuration
    "MonitorConfig",
    "NaNDetectionConfig",
    "CheckpointConfig",
    "EarlyStoppingConfig",
    "LoggingConfig",
    "ScalarLoggingConfig",
    "ImageLoggingConfig",
    "PredictionSavingConfig",
    "WandbConfig",
    # Inference configuration
    "InferenceConfig",
    "InferenceDataConfig",
    "SlidingWindowConfig",
    "TestTimeAugmentationConfig",
    "SavePredictionConfig",
    "PostprocessingConfig",
    "BinaryPostprocessingConfig",
    "ConnectedComponentsConfig",
    "EvaluationConfig",
    "DecodeModeConfig",
    "DecodeBinaryContourDistanceWatershedConfig",
    # Test configuration
    "TestConfig",
    # Tuning configuration
    "TuneOutputConfig",
    "ParameterConfig",
    "DecodingParameterSpace",
    "PostprocessingParameterSpace",
    "ParameterSpaceConfig",
    "TuneConfig",
    # Augmentation configuration
    "AugmentationConfig",
    "FlipConfig",
    "AffineConfig",
    "RotateConfig",
    "ElasticConfig",
    "IntensityConfig",
    "MisalignmentConfig",
    "MissingSectionConfig",
    "MotionBlurConfig",
    "CutNoiseConfig",
    "CutBlurConfig",
    "MissingPartsConfig",
    "StripeConfig",
    "MixupConfig",
    "CopyPasteConfig",
    # Utility functions
    "configure_edge_mode",
    "configure_instance_segmentation",
]
