# CellMap Challenge - Phase 1: Simple Instance Validation
#
# PHASE 1: Make sure simple one works
# - 1 instance class (mitochondria)
# - Binary mask output
# - SDT (Signed Distance Transform) for instance separation
#
# This config validates the instance segmentation pipeline:
# - Higher resolution (4nm) for better boundary detection
# - Binary mask prediction (sigmoid activation)
# - Post-processing: Binary mask → SDT → Watershed → Instance IDs
#
# Mitochondria is the hardest instance segmentation task:
# - High density, touching objects, complex shapes
# - Appears in 14/16 test crops
# - Critical for overall challenge score
#
# Usage:
#   python scripts/cellmap/train_cellmap.py --config tutorials/cellmap_mito.yaml

experiment_name: cellmap_mito_mednext_l
description: CellMap mitochondria instance segmentation with MedNeXt-L

# System
system:
  training:
    num_gpus: 1
    num_cpus: 4
    num_workers: 4
    batch_size: 1                      # Smaller batch for larger model + higher res
  inference:
    num_gpus: 1
    num_cpus: 1
    num_workers: 1
    batch_size: 1
  seed: 42

# Model Configuration
model:
  architecture: mednext               # MedNeXt (SOTA for instance segmentation)

  # Input/output configuration
  input_size: [96, 96, 96]            # Smaller patches for 4nm resolution
  output_size: [96, 96, 96]
  in_channels: 1                      # Grayscale EM
  out_channels: 1                     # Binary mitochondria segmentation

  # MedNeXt configuration (optimized for single class)
  mednext_size: L                     # L (61.8M params) - best for single class
  mednext_kernel_size: 7              # 7x7x7 kernels for better context
  deep_supervision: true              # Multi-scale loss (CRITICAL for quality)

  # Loss configuration (binary segmentation)
  loss_functions: [DiceLoss, BCEWithLogitsLoss]
  loss_weights: [1.0, 1.0]
  loss_kwargs:
    - {sigmoid: true, smooth_nr: 1e-5, smooth_dr: 1e-5}  # Dice
    - {reduction: mean}                                    # BCE

# Data - CellMap Challenge Dataset
data:
  # Dataset type (custom for CellMap)
  dataset_type: cellmap

  # CellMap-specific configuration
  cellmap:
    # Data paths
    data_root: /projects/weilab/dataset/cellmap
    datasplit_path: tutorials/cellmap_mito_datasplit.csv  # Auto-generated next to YAML if missing

    # Single class: mitochondria
    classes: [mito]
    force_all_classes: both           # Keep crops with mito in both train/val

    # Patch configuration (higher resolution)
    input_array_info:
      shape: [96, 96, 96]
      scale: [4, 4, 4]                # 4nm isotropic - higher res for boundaries
    target_array_info:
      shape: [96, 96, 96]
      scale: [4, 4, 4]

    # Spatial augmentation (CellMap format)
    spatial_transforms:
      mirror:
        axes: {x: 0.5, y: 0.5, z: 0.5}
      transpose:
        axes: [x, y, z]
      rotate:
        axes:
          x: [-180, 180]
          y: [-180, 180]
          z: [-180, 180]

  # Training configuration
  iter_num_per_epoch: 2000            # Steps per epoch
  persistent_workers: true

# Optimizer - AdamW with lower LR for larger model
optimization:
  max_epochs: 1000                    # Extended training for quality
  gradient_clip_val: 1.0
  accumulate_grad_batches: 8          # Effective batch = 1 * 8 = 8
  precision: "16-mixed"

  optimizer:
    name: AdamW
    lr: 5e-4                          # Lower LR for large model
    weight_decay: 1e-4

  # Scheduler - constant LR (MedNeXt recommendation)
  scheduler:
    name: constant

# Monitoring
monitor:
  detect_anomaly: false

  logging:
    scalar:
      loss: [train_loss_total_epoch]
      loss_every_n_steps: 50
      val_check_interval: 1.0
      benchmark: true

    images:
      enabled: true
      max_images: 2
      num_slices: 4
      log_every_n_epochs: 10
      channel_mode: all

  # Checkpointing
  checkpoint:
    mode: min
    save_top_k: 3
    save_last: true
    save_every_n_epochs: 50
    dirpath: outputs/cellmap_mito/checkpoints/
    use_timestamp: true

  # Early stopping (patient for long training)
  early_stopping:
    enabled: true
    monitor: train_loss_total_epoch
    patience: 100                     # Patient for 1000 epoch training
    mode: min
    min_delta: 1e-5

# Inference configuration
inference:
  sliding_window:
    window_size: [96, 96, 96]
    sw_batch_size: 1
    overlap: 0.5                      # Higher overlap for better boundaries
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: replicate

  test_time_augmentation:
    flip_axes: null                   # All flip augmentations
    rotation90_axes: null
    select_channel: all
    channel_activations:
      - [0, 1, sigmoid]               # Binary segmentation
    ensemble_mode: mean
    apply_mask: false

  save_prediction:
    enabled: true
    intensity_scale: -1

# Test configuration
test:
  data:
    test_image: null
    test_label: null
    test_mask: null
    test_resolution: [4, 4, 4]

  evaluation:
    enabled: false
    metrics: []
