_base_: bases/mednext.yaml
experiment_name: fiber_mednext_bcs
description: Fiber segmentation with MedNeXt and multi-task learning (Binary + Contour + SDT)
system:
  training:
    num_gpus: -1
    num_workers: -1
    batch_size: 8
  inference:
    num_workers: 1
    batch_size: 8
  seed: 42
model:
  debug_on_nan: false
  enable_nan_detection: true
  out_channels: 3
  input_size:
  - 32
  - 128
  - 128
  output_size:
  - 32
  - 128
  - 128
  mednext_size: S
  mednext_kernel_size: 3
  deep_supervision: false
  loss_functions:
  - WeightedBCEWithLogitsLoss
  - DiceLoss
  - WeightedBCEWithLogitsLoss
  - DiceLoss
  - WeightedMSELoss
  loss_weights:
  - 1.0
  - 0.5
  - 1.0
  - 0.5
  - 4.0
  loss_kwargs:
  - reduction: mean
  - sigmoid: true
    smooth_nr: 1e-5
    smooth_dr: 1e-5
  - reduction: mean
  - sigmoid: true
    smooth_nr: 1e-5
    smooth_dr: 1e-5
  - tanh: true
  multi_task_config:
  - - 0
    - 1
    - binary
    - - 0
      - 1
  - - 1
    - 2
    - instance_boundary
    - - 2
      - 3
  - - 2
    - 3
    - skeleton_aware_edt
    - - 4
data:
  train_path: /projects/weilab/dataset/barcode/2026/PT37_round2/
  train_image:
  - "*raw.tif"  
  train_label:
  - "*mask.tif"
  train_resolution:
  - 40
  - 16
  - 16
  use_preloaded_cache_train: true  
  persistent_workers: true
  patch_size: [32, 128, 128]
  iter_num_per_epoch: 1000 
  nnunet_preprocessing:
    enabled: true
    crop_to_nonzero: true
    normalization: zscore
    normalization_use_nonzero_mask: true
    clip_percentile_low: 0.005
    clip_percentile_high: 0.995

  label_transform:
    targets:
    - name: binary
      kwargs: {}
    - name: instance_boundary
      kwargs:
        thickness: 1
        edge_mode: all
        mode: 2d
    - name: skeleton_aware_edt
      kwargs:
        resolution:
        - 40
        - 16
        - 16
        alpha: 1
        bg_value: -1.0
        relabel: true
  augmentation:
    preset: some
    flip:
      enabled: true
    rotate:
      enabled: true
      spatial_axes:
      - 1
      - 2    
    intensity:
      enabled: true
      gaussian_noise_prob: 0
      gaussian_noise_std: 0.5
      shift_intensity_prob: 0.5
      shift_intensity_offset: 0.1
      contrast_prob: 0.5
      contrast_range: [0.9, 1.1]
optimization:
  max_epochs: 500
  gradient_clip_val: 0.5
  accumulate_grad_batches: 1
  precision: "16-mixed"
  log_every_n_steps: 100  
  optimizer:
    lr: 0.0003
    weight_decay: 0.01
    eps: 1.0e-08
  scheduler:
    name: WarmupCosineLR
    warmup_epochs: 3
    warmup_start_lr: 1.0e-05
    min_lr: 1.0e-06
  ema:
    enabled: true
    decay: 0.999
    validate_with_ema: true    
monitor:
  logging:
    scalar:
      loss:
      - train_loss_total_epoch
      loss_every_n_steps: 10      
    images:
      max_images: 2
      num_slices: 4
      log_every_n_epochs: 5
  checkpoint:
    save_top_k: 3
    save_every_n_epochs: 5
  early_stopping:
    monitor: train_loss_total_epoch
    patience: 100
    min_delta: 1.0e-05
    threshold: 0.01
    divergence_threshold: 100.0

test:
  data:
    test_path: /projects/weilab/dataset/barcode/2026/PT37_round2/
    test_image:
    - "*raw.tif"
    test_label:
    - "*mask.tif"
    test_resolution:
    - 40
    - 16
    - 16
inference:
  sliding_window:
    window_size:
    - 32
    - 128
    - 128
    overlap: 0.5
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: reflect    
  test_time_augmentation:
    enabled: true
    channel_activations:
    - - 0
      - 1
      - sigmoid
    - - 1
      - 2
      - sigmoid
    - - 2
      - 3
      - tanh
  decoding:
  - name: decode_binary_contour_distance_watershed
    kwargs:
      binary_threshold:
      - 0.9
      - 0.85
      contour_threshold:
      - 0.8
      - 1.1
      distance_threshold:
      - 0.5
      - -0.5
      min_instance_size: 100
      min_seed_size: 20
      prediction_scale: 1
  evaluation:
    enabled: true
    metrics:
    - adapted_rand
