_base_: bases/mednext.yaml

description: MitoEM 3D mitochondria instance segmentation with MedNeXt using SDT only
system:
  training:
    num_cpus: 8
    num_workers: 8
    batch_size: 4
  inference:
    num_cpus: 1
    num_workers: 1
    batch_size: 1
  seed: 42
model:
  input_size:
  - 32
  - 256
  - 256
  output_size:
  - 32
  - 256
  - 256
  out_channels: 1
  mednext_size: M
  mednext_kernel_size: 7
  mednext_dim: 3d
  deep_supervision: true
  loss_functions:
  - WeightedMSELoss
  loss_weights:
  - 1.0
  loss_kwargs:
  - tanh: true
data:
  train_path: /projects/weilab/dataset/mito/mitoEM/
  train_resolution:
  - 30
  - 8
  - 8
  use_preloaded_cache: true
  cache_rate: 1.0
  persistent_workers: true
  patch_size:
  - 32
  - 256
  - 256
  pad_size:
  - 4
  - 16
  - 16
  pad_mode: reflect
  iter_num_per_epoch: 2000
  image_transform:
    clip_percentile_low: 0.005
    clip_percentile_high: 0.995
  label_transform:
    targets:
    - name: instance_edt
      kwargs:
        mode: 3d
        quantize: false
        normalize: true
  augmentation:
    preset: all
optimization:
  max_epochs: 1000
  accumulate_grad_batches: 2
  precision: bf16-mixed
  deterministic: false
  benchmark: true
  optimizer:
    lr: 0.0003
    weight_decay: 1e-4
    eps: 1.0e-08
  scheduler:
    name: WarmupCosineLR
    warmup_epochs: 20
    warmup_start_lr: 3.0e-05
    min_lr: 1.0e-06
    interval: epoch
    frequency: 1
  ema:
    enabled: true
    decay: 0.999
    warmup_steps: 500
    validate_with_ema: true
monitor:
  logging:
    scalar:
      loss:
      - train_loss_total_epoch
      - val_loss_total
      - val_loss_total_epoch
      loss_every_n_steps: 100
      val_check_interval: 1.0
    images:
      max_images: 4
      num_slices: 8
      log_every_n_epochs: 5
  checkpoint:
    monitor: val_loss_total_epoch
    save_top_k: 5
    save_every_n_epochs: 10
  early_stopping:
    enabled: false
test:
  data:
    test_resolution:
    - 30
    - 8
    - 8
inference:
  sliding_window:
    window_size:
    - 32
    - 256
    - 256
    sw_batch_size: 4
    overlap: 0.5
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: replicate
  test_time_augmentation:
    enabled: true
    rotation90_axes: null
    channel_activations:
    - - 0
      - 1
      - tanh
    select_channel: all
    apply_mask: false
  save_prediction:
    enabled: true
    intensity_scale: -1
    intensity_dtype: float32
  decoding:
  - name: decode_distance_watershed
    kwargs:
      distance_threshold:
      - 0.5
      - 0
      min_instance_size: 100
      min_seed_size: 50
      prediction_scale: 1
  evaluation:
    enabled: true
    metrics:
    - adapted_rand
    - voi
