_base_: bases/mednext.yaml
experiment_name: cem-mitolab_mednext2d
description: Mitochondria segmentation on CEM-MitoLab dataset using MedNeXt 2D
system:
  training:
    num_gpus: 1
    num_workers: 0
    batch_size: 16
  inference:
    num_workers: 4
    batch_size: 32
  seed: 42
model:
  out_channels: 3
  mednext_size: S
  mednext_kernel_size: 3
  mednext_dim: 2d
  deep_supervision: true
  losses:
    - function: DiceLoss
      weight: 1.0
      kwargs: {include_background: false, sigmoid: true, smooth_nr: 1e-5, smooth_dr: 1e-5}
      pred_slice: [0, 1]
      target_slice: [0, 1]
    - function: BCEWithLogitsLoss
      weight: 0.5
      pred_slice: [0, 1]
      target_slice: [0, 1]
    - function: BCEWithLogitsLoss
      weight: 0.5
      pred_slice: [1, 2]
      target_slice: [1, 2]
    - function: WeightedMSELoss
      weight: 1.0
      kwargs: {tanh: true}
      pred_slice: [2, 3]
      target_slice: [2, 3]
data:
  dataset_type: filename
  train_json: datasets/cem-mitolab/files.json
  train_image_key: images
  train_label_key: masks
  train_val_split: 0.9
  train_resolution:
    - 0
    - 5
    - 5
  patch_size:
    - 224
    - 224
  pad_size:
    - 0
    - 0
  iter_num_per_epoch: -1
  use_preloaded_cache: false
  image_transform:
    clip_percentile_low: 0.0
    clip_percentile_high: 1.0
  label_transform:
    targets:
      - name: binary
      - name: instance_boundary
        kwargs:
          thickness: 1
          edge_mode: seg-all
          mode: 2d
      - name: instance_edt
        kwargs:
          mode: 2d
          quantize: false
  augmentation:
    preset: all
optimization:
  max_epochs: 100
  accumulate_grad_batches: 1
  precision: bf16-mixed
  optimizer:
    lr: 0.001
    weight_decay: 0.01
    eps: 1.0e-08
  scheduler:
    name: StepLR
    step_size: 100000
    gamma: 1.0
monitor:
  logging:
    scalar:
      loss:
        - train_loss_total_epoch
      loss_every_n_steps: 50
    images:
      max_images: 16
      num_slices: 1
      log_every_n_epochs: 1
  checkpoint:
    monitor: val/loss
    save_top_k: 3
    save_every_n_epochs: 1
    dirpath: outputs/cem-mitolab_mednext2d/checkpoints/
    checkpoint_filename: epoch={epoch:03d}-val_loss={val/loss:.4f}
  early_stopping:
    monitor: in_loss_total_epoch
    patience: 20
    min_delta: 0.0001
    threshold: 0.05
    divergence_threshold: 2.0
test:
  data:
    test_image: datasets/cem-mitolab/test.json
    test_label:
    test_resolution:
      - 0
      - 5
      - 5
    output_path: outputs/cem-mitolab_mednext2d/results/
inference:
  test_time_augmentation:
    enabled: false
    channel_activations:
      -   - 0
          - 2
          - sigmoid
      -   - 2
          - 3
          - tanh
    select_channel:
  save_prediction:
    enabled: true
    intensity_scale: 255
    intensity_dtype: uint8
  evaluation:
    enabled: false
    metrics: []
