_base_: bases/mednext.yaml
experiment_name: mitoem_mednext_sdt
description: MitoEM 3D mitochondria instance segmentation with MedNeXt using SDT only
system:
  training:
    num_gpus: 4
    num_cpus: 8
    num_workers: 8
    batch_size: 16
  inference:
    num_cpus: 1
    num_workers: 1
    batch_size: 1
  seed: 42
model:
  input_size:
  - 16
  - 256
  - 256
  output_size:
  - 16
  - 256
  - 256
  out_channels: 1
  mednext_size: M
  mednext_kernel_size: 7
  mednext_dim: 3d
  deep_supervision: true
  loss_functions:
  - WeightedMSELoss
  loss_weights:
  - 1.0
  loss_kwargs:
  - tanh: true
data:
  train_path: /projects/weilab/dataset/mito/mitoEM/
  train_image:
  - EM30-H/im_train_val.h5
  train_label:
  - EM30-H/mito_train_val.h5
  train_resolution:
  - 30
  - 8
  - 8
  use_preloaded_cache: true
  cache_rate: 1.0
  persistent_workers: true
  patch_size:
  - 16
  - 256
  - 256
  pad_size:
  - 4
  - 16
  - 16
  pad_mode: reflect
  iter_num_per_epoch: 2000
  image_transform:
    clip_percentile_low: 0.005
    clip_percentile_high: 0.995
  label_transform:
    targets:
    - name: instance_edt
      kwargs:
        mode: 3d
        quantize: false
        normalize: true
  augmentation:
    preset: all
optimization:
  max_epochs: 1000
  accumulate_grad_batches: 4
  precision: 16-mixed
  optimizer:
    lr: 0.001
    weight_decay: 1e-4
    eps: 1.0e-08
  scheduler:
    name: constant
monitor:
  logging:
    scalar:
      loss:
      - train_loss_total_epoch
      loss_every_n_steps: 50
      val_check_interval: 1.0
    images:
      max_images: 4
      num_slices: 8
      log_every_n_epochs: 5
  checkpoint:
    save_top_k: 5
    save_every_n_epochs: 25
    dirpath: outputs/mitoem_mednext_sdt/checkpoints/
  early_stopping:
    monitor: train_loss_total_epoch
    patience: 150
    min_delta: 1e-6
    threshold: 0.01
    divergence_threshold: 100.0
test:
  data:
    test_image: /projects/weilab/dataset/mito/mitoEM/EM30-H/im_test.h5
    test_label: /projects/weilab/dataset/mito/mitoEM/EM30-H/mito_test.h5
    test_resolution:
    - 30
    - 8
    - 8
    output_path: outputs/mitoem_mednext_sdt/results/
inference:
  sliding_window:
    window_size:
    - 16
    - 256
    - 256
    sw_batch_size: 4
    overlap: 0.5
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: replicate
  test_time_augmentation:
    enabled: true
    rotation90_axes: null
    channel_activations:
    - - 0
      - 1
      - tanh
    select_channel: all
    apply_mask: false
  save_prediction:
    enabled: true
    intensity_scale: -1
    intensity_dtype: float32
  decoding:
  - name: decode_distance_watershed
    kwargs:
      distance_threshold:
      - 0.5
      - 0
      min_instance_size: 100
      min_seed_size: 50
      prediction_scale: 1
  evaluation:
    enabled: true
    metrics:
    - adapted_rand
    - voi
