_base_: bases/rsunet.yaml
experiment_name: rsunet_snemi_aug3_long
description: SNEMI3D neuron segmentation with RSUNet (long-range affinities, EM augmentations)
system:
  training:
    batch_size: 8
  inference:
    batch_size: 1
  seed: 42
model:
  out_channels: 12
  filters:
  - 36
  - 48
  - 64
  - 80
  rsunet_norm: batch
  rsunet_activation: elu
  rsunet_num_groups: 8
  rsunet_down_factors:
  - - 1
    - 2
    - 2
  - - 1
    - 2
    - 2
  - - 1
    - 2
    - 2
  rsunet_depth_2d: 1
  rsunet_kernel_2d:
  - 1
  - 3
  - 3
  deep_supervision: false
  loss_functions:
  - WeightedBCEWithLogitsLoss
  loss_weights:
  - 1.0
  loss_kwargs:
  - pos_weight: 10.0
data:
  train_image: datasets/SNEMI/train-input.tif
  train_label: datasets/SNEMI/train-labels.tif
  patch_size:
  - 16
  - 160
  - 160
  pad_size:
  - 0
  - 0
  - 0
  iter_num_per_epoch: 1280
  use_preloaded_cache: true
  image_transform:
    clip_percentile_low: 0.0
    clip_percentile_high: 1.0
  label_transform:
    erosion: 1
    targets:
    - name: affinity
      kwargs:
        offsets:
        - 0-0-1
        - 0-1-0
        - 1-0-0
        - 2-0-0
        - 3-0-0
        - 4-0-0
        - 0-0-3
        - 0-0-9
        - 0-0-27
        - 0-3-0
        - 0-9-0
        - 0-27-0
  augmentation:
    preset: some
    flip:
      enabled: true
      prob: 0.5
      spatial_axis:
      - 0
      - 1
      - 2
    rotate:
      enabled: true
      prob: 0.5
      max_angle: 90.0
    elastic:
      enabled: true
      prob: 0.7
      sigma_range:
      - 4.0
      - 8.0
      magnitude_range:
      - 8.0
      - 16.0
    intensity:
      enabled: true
      gaussian_noise_prob: 0.3
      gaussian_noise_std: 0.05
      shift_intensity_prob: 0.7
      shift_intensity_offset: 0.2
      contrast_prob: 0.7
      contrast_range:
      - 0.5
      - 1.5
    misalignment:
      enabled: true
      prob: 0.5
      displacement: 17
      rotate_ratio: 0.5
    missing_section:
      enabled: true
      prob: 0.3
      num_sections: 5
    motion_blur:
      enabled: true
      prob: 0.3
      sections: 2
      kernel_size: 11
    cut_noise:
      enabled: false
    cut_blur:
      enabled: false
    missing_parts:
      enabled: false
optimization:
  max_epochs: 500
  gradient_clip_val: 0.0
  accumulate_grad_batches: 1
  precision: bf16-mixed
  deterministic: false
  benchmark: true
  optimizer:
    name: Adam
    lr: 0.01
    eps: 0.01
    weight_decay: 0.0
  scheduler:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 10000
    min_lr: 6.25e-05
    threshold: 0.0001
    cooldown: 0
    monitor: train_loss_total_epoch
monitor:
  logging:
    scalar:
      loss:
      - train_loss_total_epoch
      loss_every_n_steps: 10
      val_check_interval: 1.0
    images:
      max_images: 8
      num_slices: 8
      log_every_n_epochs: 1
      channel_mode: all
  checkpoint:
    monitor: val/loss
    save_top_k: 3
    save_every_n_epochs: 10
    dirpath: outputs/rsunet_snemi_aug3_long/checkpoints/
    checkpoint_filename: epoch={epoch:03d}-step={step:07d}-val_loss={val/loss:.4f}
  early_stopping:
    enabled: false
test:
  data:
    test_image: datasets/SNEMI/train-input.tif
    test_label: datasets/SNEMI/train-labels.tif
    test_resolution:
    - 30
    - 6
    - 6
    output_path: outputs/rsunet_snemi_aug3_long/results/
inference:
  sliding_window:
    window_size:
    - 16
    - 180
    - 180
    sw_batch_size: 4
    overlap: 0.5
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: reflect
  test_time_augmentation:
    enabled: true
    flip_axes: null
    channel_activations:
    - - 0
      - 12
      - softmax
    select_channel:
    - 1
  save_prediction:
    enabled: true
    intensity_scale: 255
    intensity_dtype: uint8
  evaluation:
    enabled: false
    metrics:
    - adapted_rand
