experiment_name: rsunet_snemi_lee2017_modern
description: SNEMI3D neuron affinity learning (2017-style short-range setup with modern optimization and stability tricks)

_base_:
  - bases/all_profiles.yaml

default:
  pipeline_profile: affinity-12
  system:
    profile: all-gpu-cpu
  model:
    arch:
      profile: rsunet
    input_size: [16, 224, 224]
    output_size: [16, 224, 224]
  data:
    dataloader:
      profile: cached
      patch_size: [16, 224, 224]
    data_transform:
      pad_size: [4, 64, 64]
  inference:
    batch_size: 8
    sliding_window:
      window_size: [16, 224, 224]
      pad_size: [4, 64, 64]
    test_time_augmentation:
      enabled: false
      flip_axes: all
    save_prediction:
      enabled: true
    evaluation:
      enabled: true
      metrics: [adapted_rand]


train:
  data:
    train:
      image: datasets/SNEMI/train-input.tif
      label: datasets/SNEMI/train-labels.tif
  optimization:
    profile: warmup_cosine_lr
    max_epochs: 100
    n_steps_per_epoch: 1000    
  monitor:
    logging:
      scalar:
        loss_every_n_steps: 50
      images:
        log_every_n_epochs: 10
        max_images: 8
        num_slices: 2
    checkpoint:
      save_top_k: 3
      monitor: train_loss_total_epoch      

test:
  data:
    test:
      path: datasets/SNEMI/
      # image: [train-input.tif, test-input_z29.h5]
      # label: [train-labels.tif, test-labels.h5]
      image: train-input.tif
      label: train-labels.tif
      resolution: [30, 6, 6]    
