# Zebrafish Neuron Instance Segmentation (2D Fluorescence)
# Small circular neurons (12-18 px diameter) with low SNR uint16 images (~180 max).
# MONAI Residual UNet with contour channel + watershed decoding for instance IDs.

experiment_name: zebrafish_neurons
description: 2D zebrafish neuron instance segmentation with MONAI UNet and watershed decoding

# System
system:
  training:
    num_gpus: 1
    num_cpus: 16
    num_workers: 16
    batch_size: 128
  inference:
    num_gpus: 1
    num_cpus: 4
    num_workers: 4
    batch_size: 64
  seed: 42

# Model Configuration
model:
  architecture: monai_unet
  input_size: [256, 256]
  output_size: [256, 256]
  in_channels: 1
  out_channels: 3                        # binary + boundary + edt (3 channels for multi-task)
  filters: [24, 48, 96, 192]
  num_res_units: 2
  kernel_size: 3
  norm: batch
  dropout: 0.1                           # Reduced dropout (was 0.15) to prevent underfitting on small objects
  
  # Deep supervision clamping to prevent numerical instability
  deep_supervision_clamp_min: -15.0      # Tighter clamping (was -20.0)
  deep_supervision_clamp_max: 15.0       # Tighter clamping (was 20.0)

  # Loss configuration - Optimized for small neurons with improved EDT handling
  # Binary/Boundary: BCE+Dice (standard), EDT: WeightedMSELoss with tanh activation
  loss_functions: [WeightedBCEWithLogitsLoss, DiceLoss, WeightedBCEWithLogitsLoss, DiceLoss, WeightedMSELoss, WeightedMAELoss]
  loss_weights: [0.5, 1.5, 0.5, 1.5, 1.0, 0.5]
  loss_kwargs:
    - {reduction: mean}                            # Binary: WeightedBCE
    - {include_background: true, sigmoid: true, smooth_nr: 1e-5, smooth_dr: 1e-5}  # Binary: Dice (higher weight for overlap)
    - {reduction: mean}                            # Boundary: WeightedBCE
    - {include_background: true, sigmoid: true, smooth_nr: 1e-5, smooth_dr: 1e-5}  # Boundary: Dice (higher weight)
    - {reduction: mean, tanh: true}                # EDT: WeightedMSE with tanh (constrains to [-1,1])
    - {reduction: mean, tanh: true}                # EDT: WeightedMAE with tanh (robust to outliers)

  # Multi-task configuration
  # Format: [[start_ch, end_ch, target_name, loss_indices], ...]
  multi_task_config:
    - [0, 1, "binary", [0, 1]]         # Original labels: Dice + BCE
    - [1, 2, "boundary", [2, 3]]       # Boundary channel: Dice + BCE  
    - [2, 3, "edt", [4, 5]]            # Distance channel: Dice + BCE  


# Data - 2D fluorescence microscopy
data:
  do_2d: true

  # Image/label locations - YOUR PATHS
  train_image: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/train/images/*.tif
  train_label: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/train/labels/*.tif
  train_resolution: [0.365, 0.365]        # micrometers: y, x
  val_image: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/val/images/*.tif
  val_label: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/val/labels/*.tif
  use_preloaded_cache: false              # Dataset too large for full in-memory cache
  use_cache: true                         # Partial cache for faster IO
  cache_rate: 0.06
  pin_memory: true
  persistent_workers: true

  # Patch sampling
  patch_size: [256, 256]
  pad_size: [0, 0]
  pad_mode: reflect
  iter_num_per_epoch: 25600

  # Image normalization
  image_transform:
    normalize: "0-1"
    clip_percentile_low: 0.01
    clip_percentile_high: 0.99

  # Label processing: binary + boundary + distance for multi-task learning
  label_transform:
    targets:
      - name: binary                     # Channel 0: Binary foreground
      - name: instance_boundary          # Channel 1: Instance boundaries
        kwargs:
          thickness: 1
          edge_mode: seg-all
          mode: 2d
      - name: instance_edt               # Channel 2: Instance Euclidean Distance Transform
        kwargs:
          mode: 2d

  # Augmentation - optimized for small neurons with low SNR
  augmentation:
    preset: some
    flip:
      enabled: true
      spatial_axis: [0, 1]
    rotate:
      enabled: true
    affine:
      enabled: false
    elastic:
      enabled: false                     # Keep disabled for small objects
    intensity:
      enabled: true
      shift_intensity_prob: 0.4          # Slightly reduced (was 0.5)
      shift_intensity_offset: 0.08       # More conservative (was 0.1)
      gaussian_noise_prob: 0.2           # Added mild noise augmentation
      gaussian_noise_std: 0.02           # Very mild noise for low SNR data
      contrast_prob: 0.4                 # Increased (was 0.3)
      contrast_range: [0.9, 1.1]         # Wider range (was [0.95, 1.05])

# Optimizer - AdamW with improved settings for small object segmentation
optimization:
  max_epochs: 600                    # Increased from 500 for better convergence
  val_check_interval: 1.0
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  precision: "bf16-mixed"

  optimizer:
    name: AdamW
    lr: 0.0005
    weight_decay: 0.005
    betas: [0.9, 0.999]
    eps: 1.0e-8

  # Scheduler - ReduceLROnPlateau for adaptive learning
  scheduler:
    name: ReduceLROnPlateau
    monitor: val_loss_total
    mode: min
    factor: 0.3
    patience: 25
    threshold: 5.0e-5
    min_lr: 5.0e-7

monitor:
  detect_anomaly: false
  logging:
    # Scalar loss logging
    scalar:
      loss: [train_loss_total_epoch]
      loss_every_n_steps: 10
      val_check_interval: 1.0
      benchmark: true

    # Visualization
    images:
      enabled: true
      max_images: 8
      num_slices: 1                      # 2D visualization
      log_every_n_epochs: 5
      channel_mode: argmax
      selected_channels: null

  # Checkpointing
  checkpoint:
    monitor: val_loss_total
    mode: min
    save_top_k: 1
    save_last: true
    save_every_n_epochs: 1
    dirpath: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/outputs/zebrafish_neurons/checkpoints/
    use_timestamp: true                  # Timestamped subdirectories (YYYYMMDD_HHMMSS)

  # Early stopping - patient for small objects
  early_stopping:
    enabled: true
    monitor: val_loss_total
    patience: 120
    mode: min
    min_delta: 5.0e-6
    check_finite: true
    threshold: 0.003
    divergence_threshold: 5.0

# Inference - Sliding window for full 1216x2048 images
inference:
  sliding_window:
    window_size: [256, 256]
    overlap: 0.5
    blending: gaussian
    sigma_scale: 0.25
    padding_mode: reflect

  test_time_augmentation:
    enabled: false
    flip_axes: [[0], [1], [0, 1]]
    channel_activations: null
    select_channel: null
    ensemble_mode: mean

  # Save intermediate predictions (pre-decoding)
  save_prediction:
    enabled: true
    intensity_scale: -1.0    

# Postprocessing - keep instance IDs
  postprocessing:
    enabled: false

test:
  data:
    # YOUR TEST PATHS
    test_image: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/val/images/124313.tif
    test_label: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/val/labels/124313.tif
    test_resolution: [0.365, 0.365]
    output_path: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/outputs/zebrafish_neurons/results/
    image_transform:
      normalize: "0-1"                     # Min-max normalization to [0, 1]
      clip_percentile_low: 0.01            # Clip bottom 1% (remove dark noise outliers)
      clip_percentile_high: 0.99           # Clip top 1% (remove bright outliers)

  # Decoding: foreground + contour -> instance labels
  decoding:
    - name: decode_instance_binary_contour_distance
      kwargs:
        binary_channels: [0]                # Channel 0: binary foreground
        contour_channels: [1]               # Channel 1: instance boundaries
        distance_channels: [2]              # Channel 2: distance transform
        binary_threshold: [0.5, 0.4]
        contour_threshold: [0.6, 0.9]
        distance_threshold: [0.4, 0.1]
        min_seed_size: 6

  # Evaluation
  evaluation:
    enabled: false
    metrics: [adapted_rand]

# Parameter tuning with Optuna
tune:
  enabled: true                     # Disable for training mode (enable only for tune mode)
  n_trials: 50
  study_name: zebrafish_neurons_tuning
  storage: "sqlite:///outputs/zebrafish_neurons/tuning/tuning.db"
  load_if_exists: true
  
  sampler:
    name: TPE
    kwargs:
      n_startup_trials: 10
      multivariate: true
  
  pruner:
    enabled: false
  
  optimization:
    mode: single
    single_objective:
      metric: adapted_rand
      direction: minimize
  
  data:
    tune_image: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/tuning_subset/images/*.tif
    tune_label: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/tuning_subset/labels/*.tif
    image_transform:
      normalize: "0-1"
      clip_percentile_low: 0.01
      clip_percentile_high: 0.99
  
  output:
    output_dir: /orcd/scratch/bcs/002/mansour/zebrafish_seg_dataset/outputs/zebrafish_neurons/tuning
    save_all_trials: false
    save_best_segmentation: true
    save_study: true
    report:
      enabled: true
      top_n_trials: 10
      format: markdown
  
  logging:
    verbose: true
    show_progress_bar: true
  
  parameter_space:
    decoding:
      function_name: decode_instance_binary_contour_distance
      defaults:
        binary_threshold: [0.6, 0.6]      
        contour_threshold: [0.65, 0.85]     
        distance_threshold: [0.45, 0.35]
        min_seed_size: 22
      parameters:
        binary_threshold_seed:
          type: float
          range: [0.50, 0.70]              
          step: 0.05
          param_group: binary_threshold
          tuple_index: 0
        binary_threshold_foreground:
          type: float
          range: [0.45, 0.60]               
          step: 0.05
          param_group: binary_threshold
          tuple_index: 1
        contour_threshold_seed:
          type: float
          range: [0.55, 0.85]              
          step: 0.05
          param_group: contour_threshold
          tuple_index: 0
        contour_threshold_foreground:
          type: float
          range: [0.85, 1.0]               
          step: 0.05
          param_group: contour_threshold
          tuple_index: 1
        distance_threshold_seed:
          type: float
          range: [0.35, 0.65]              
          step: 0.05
          param_group: distance_threshold
          tuple_index: 0
        distance_threshold_foreground:
          type: float
          range: [0.30, 0.50]               
          step: 0.05
          param_group: distance_threshold
          tuple_index: 1
        min_seed_size:
          type: int
          range: [12, 24]                   
          step: 2
