_base_:
  - base_banis.yaml

experiment_name: nisb_base_banis_erosion2
description: BANIS train_base_long reproduction target with label erosion=2

save_path: outputs/nisb_base_banis_erosion2

default:
  data:
    dataloader:
      batch_size: 4
    label_transform:
      erosion: 2

