pipeline_profiles:
  binary:
    model:
      out_channels: 1
      loss:
        profile: loss_binary
    inference:
      test_time_augmentation:
        activation_profile: act_binary

  bcd:
    model:
      out_channels: 3
      loss:
        profile: loss_bcd
    data:
      label_transform:
        profile: label_bcd
    inference:
      decoding:
        - template: decoding_bcd
      test_time_augmentation:
        ensemble_mode: mean
        activation_profile: act_bcd
  aff9:
    model:
      out_channels: 9
      loss:
        profile: loss_per_channel
    data:
      label_transform:
        profile: label_aff9
    inference:
      decoding:
        - template: decoding_waterz
      test_time_augmentation:
        ensemble_mode: min
        activation_profile: act_binary
  aff12:
    model:
      out_channels: 12
      loss:
        profile: loss_per_channel
    data:
      label_transform:
        profile: label_aff12
    inference:
      select_channel: [0, 1, 2]
      decoding:
        - template: decoding_waterz
      test_time_augmentation:
        ensemble_mode: min
        activation_profile: act_binary
  aff9_sdt:
    model:
      out_channels: 10
      loss:
        profile: loss_bd
    data:
      label_transform:
        profile: label_aff9_sdt
    inference:
      decoding:
        - template: decoding_waterz
      test_time_augmentation:
        ensemble_mode: [["0:9", min], ["9:", mean]]
        activation_profile: act_bd
